version: "3.8"

services:
  cryptoboard:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DEBUG: "False"
      POSTGRES_DB_NAME: db
      POSTGRES_DB_HOST: db
      POSTGRES_DB_PORT: 5432
      POSTGRES_DB_USERNAME: test
      POSTGRES_DB_PASSWORD: test
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - default

  db:
    image: postgres:latest
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -t 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s
    networks:
      - default

networks:
  default:
